### ISSUE TITLE
Add OpenVINO by Intel?

### ISSUE THREAD

**Issue by jhallard** [valohai/ml-logos#6]
First off, thank you! This was literally exactly what I was looking for.

Secondly, is it possible to add something for Intel OpenVINO (https://software.intel.com/en-us/openvino-toolkit?cid=sem43700033924626572&intel_term=intel+openvino&gclid=Cj0KCQjwlqLdBRCKARIsAPxTGaUsTq_4_g7Bb3xjqAdqYKZ1mBbYuaIgd_dyM-8VuEbCHZYRMnTIuDYaAhqMEALw_wcB&gclsrc=aw.ds)?

**Comment by akx** [comment]
Thank you! Glad to be of service. Making these is a fun occasional diversion from writing actual platform code anyway. 😅 

Sorry it took a while – [here you go!](https://github.com/valohai/ml-logos/blob/811854fd849df40f099c3ff6a8f07b3e4914665d/openvino-toolkit.svg)

**Comment by evgen48** [comment]
https://01.org/sites/default/files/openvino-square.png

**Comment by akx** [comment]
@evgen48 Thanks! Added in f7a9a06
